[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false

[workspace]
members = [
    "dpdk-rs",
    "catnip",
    "catnip-libos",
    "catnap-libos",
]
